version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: platform
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"

  ingest:
    build: ./ingest
    depends_on: [minio]
    environment:
      MINIO_ENDPOINT: http://minio:9000

  transform:
    build: ./transform
    depends_on: [postgres, minio]

  validate:
    build: ./validate
    depends_on: [postgres]

  dbt:
    build: ./dbt
    depends_on: [postgres]
    command: ["run"]

  # ml:
  #   build: ./ml
  #   depends_on: [postgres]

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3101:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./observability/loki/config.yml:/etc/loki/config.yml
      - ./observability/loki/data:/loki
      - ./observability/loki/data/wal:/wal

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./observability/promtail/config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOGS_ENABLED=true
